### ISSUE TITLE
NgSwitchCase Instead of NgSwitchWhen

### ISSUE THREAD

**Issue by nishant07kumar** [colinjlacy/angular-2-loading-container#1]
Hi First of all want to say really nice loading spinner. saved my day.
I want to mention worked for me once i replaced NgSwitchWhen with NgSwitchCase below two places in 
loading-container.ts

import {NgSwitch, NgSwitchCase}  from '@angular/common';

 directives: [NgSwitch, NgSwitchCase]

May be depend on angular 2 version.

Thanks,
Nishant Kumar
Markit

**Comment by colinjlacy** [comment]
Might be.  I'll create a branch with the latest RC and confirm.  Thanks for the heads up!

**Comment by colinjlacy** [comment]
You're absolutely correct.  Confirmed with the API docs.  Merged in an update.  Thanks again for catching it and letting me know!

**Comment by nishant07kumar** [comment]
your welcome. :)
